services:
  - type: web
    name: sfit-api-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: sfit-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: sfit-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: sfit-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: sfit-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: sfit-db
          property: password
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true

databases:
  - name: sfit-db
    plan: free
    databaseName: sfit
    user: sfit_user

version: "1"
